// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.winry.mahjong.message



object MessageProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChNwcm90by9tZXNzYWdlLnByb3RvEgdtZXNzYWdlIo0CCglQYWNrZXRNU0cSLwoIbG9naW5SZXEYASABKAsyES5tZXNzYWdlL
  kxvZ2luUmVxSABSCGxvZ2luUmVxEi8KCHJlYWR5UmVxGAIgASgLMhEubWVzc2FnZS5SZWFkeVJlcUgAUghyZWFkeVJlcRIvCghyZ
  WFjaFJlcRgDIAEoCzIRLm1lc3NhZ2UuUmVhY2hSZXFIAFIIcmVhY2hSZXESLwoIdHN1bW9SZXEYBCABKAsyES5tZXNzYWdlLlRzd
  W1vUmVxSABSCHRzdW1vUmVxEjUKCmRpc2NhcmRSZXEYBSABKAsyEy5tZXNzYWdlLkRpc2NhcmRSZXFIAFIKZGlzY2FyZFJlcUIFC
  gNtc2ciHgoITG9naW5SZXESEgoEbmFtZRgBIAEoCVIEbmFtZSIbCglMb2dpblJlc3ASDgoCaWQYASABKANSAmlkIgoKCFJlYWR5U
  mVxIg8KDUdhbWVTdGFydFJlc3AiWAoIUmVhY2hSZXESFgoGZ2FtZUlkGAEgASgDUgZnYW1lSWQSFgoGdXNlcklkGAIgASgDUgZ1c
  2VySWQSHAoJdG9EaXNjYXJkGAMgASgFUgl0b0Rpc2NhcmQiCwoJUmVhY2hSZXNwIjoKCFRzdW1vUmVxEhYKBmdhbWVJZBgBIAEoA
  1IGZ2FtZUlkEhYKBnVzZXJJZBgCIAEoA1IGdXNlcklkIloKCkRpc2NhcmRSZXESFgoGZ2FtZUlkGAEgASgDUgZnYW1lSWQSFgoGd
  XNlcklkGAIgASgDUgZ1c2VySWQSHAoJdG9EaXNjYXJkGAMgASgFUgl0b0Rpc2NhcmRCEwoRY29tLndpbnJ5Lm1haGpvbmdiBnByb
  3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}