// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.winry.mahjong.message



object MessageProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChNwcm90by9tZXNzYWdlLnByb3RvEgdtZXNzYWdlIsECCglQYWNrZXRNU0cSLwoIbG9naW5SZXEYASABKAsyES5tZXNzYWdlL
  kxvZ2luUmVxSABSCGxvZ2luUmVxEi8KCHJlYWR5UmVxGAIgASgLMhEubWVzc2FnZS5SZWFkeVJlcUgAUghyZWFkeVJlcRIvCghyZ
  WFjaFJlcRgDIAEoCzIRLm1lc3NhZ2UuUmVhY2hSZXFIAFIIcmVhY2hSZXESLwoIdHN1bW9SZXEYBCABKAsyES5tZXNzYWdlLlRzd
  W1vUmVxSABSCHRzdW1vUmVxEjUKCmRpc2NhcmRSZXEYBSABKAsyEy5tZXNzYWdlLkRpc2NhcmRSZXFIAFIKZGlzY2FyZFJlcRIyC
  gloZWFydGJlYXQYBiABKAsyEi5tZXNzYWdlLkhlYXJ0YmVhdEgAUgloZWFydGJlYXRCBQoDbXNnIh4KCExvZ2luUmVxEhIKBG5hb
  WUYASABKAlSBG5hbWUiGwoJTG9naW5SZXNwEg4KAmlkGAEgASgDUgJpZCIKCghSZWFkeVJlcSIPCg1HYW1lU3RhcnRSZXNwIigKC
  FJlYWNoUmVxEhwKCXRvRGlzY2FyZBgBIAEoBVIJdG9EaXNjYXJkIgsKCVJlYWNoUmVzcCIKCghUc3Vtb1JlcSIqCgpEaXNjYXJkU
  mVxEhwKCXRvRGlzY2FyZBgBIAEoBVIJdG9EaXNjYXJkIgsKCUhlYXJ0YmVhdEITChFjb20ud2lucnkubWFoam9uZ2IGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}