// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.winry.mahjong.message



object MessageProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChNwcm90by9tZXNzYWdlLnByb3RvEgdtZXNzYWdlIqgBCglQYWNrZXRNU0cSLwoIbG9naW5SZXEYASABKAsyES5tZXNzYWdlL
  kxvZ2luUmVxSABSCGxvZ2luUmVxEjIKCWxvZ2luUmVzcBgCIAEoCzISLm1lc3NhZ2UuTG9naW5SZXNwSABSCWxvZ2luUmVzcBIvC
  ghyZWFkeVJlcRgDIAEoCzIRLm1lc3NhZ2UuUmVhZHlSZXFIAFIIcmVhZHlSZXFCBQoDbXNnIh4KCExvZ2luUmVxEhIKBG5hbWUYA
  SABKAlSBG5hbWUiGwoJTG9naW5SZXNwEg4KAmlkGAEgASgDUgJpZCIKCghSZWFkeVJlcSIPCg1HYW1lU3RhcnRSZXNwQhMKEWNvb
  S53aW5yeS5tYWhqb25nYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}