// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.winry.mahjong.message



object PacketProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChJwcm90by9wYWNrZXQucHJvdG8SBnBhY2tldCJ1CglQYWNrZXRNU0cSLgoIbG9naW5SZXEYASABKAsyEC5wYWNrZXQuTG9na
  W5SZXFIAFIIbG9naW5SZXESMQoJbG9naW5SZXNwGAIgASgLMhEucGFja2V0LkxvZ2luUmVzcEgAUglsb2dpblJlc3BCBQoDbXNnI
  h4KCExvZ2luUmVxEhIKBG5hbWUYASABKAlSBG5hbWUiGwoJTG9naW5SZXNwEg4KAmlkGAEgASgDUgJpZEITChFjb20ud2lucnkub
  WFoam9uZ2IGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}